version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app/src/Dockerfile
    ports:
      - "3000:8080"
    tty: true
    env_file:
      - ./app/src/.env
    depends_on:
      - db
    volumes:
      - ./app/src/:/go/src


  db:
    image: mysql:8.0
    environment:
      TZ: 'Asia/Tokyo'
    env_file:
      - ./app/src/.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/db:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  react:
    build:
      args:
        - NODE_VER=16.17.1-slim
      context: ./client
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./client:/home/node/app
      - ./client/node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173

volumes:
  db-data:
    driver: local